# Generated by Django 3.2 on 2021-04-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210425_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
